refstudio/refstudio

.gitignore, README.md, package.json, poetry.lock, pyproject.toml, scripts/move_binary.py, src-python/main.py, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/tauri.conf.json, src/App.tsx
- https://github.com/refstudio/refstudio/issues/17
This is a very basic PoC for the sidecar pattern and sets up some general scaffolding.
Some things to note:
1. It adds poetry to manage python dependencies
2. It uses [PyInstaller](https://pyinstaller.org/en/stable/) to package up a single executable to act as the side car. Tauri requires a `-$TARGET_TRIPLE` be specified in the binary filepath, so that happens via `scripts/move_binary.py`.
=> Python sidecar

src/App.tsx, src/TipTapEditor/MenuBar.css, src/TipTapEditor/MenuBar.tsx, src/TipTapEditor/TipTapEditor.tsx, src/views/AIView.tsx, src/views/CenterPaneView.tsx, src/views/FoldersView.tsx, src/views/ReferencesView.tsx
**Problem**
Panel components have an `overflow` property set to `hidden`, that is why adding the tailwind `overflow-scroll` class does not make the views scrollable. #35 
**Solution**
Remove `overflow-scroll` class and make views flexes, with a scrollable child
https://github.com/refstudio/refstudio/assets/58954208/ee89dc39-8969-4a60-8b5c-59f8a1fcc2ea
=> fix: allow flexboxes to scroll

.husky/pre-push, package.json, poetry.lock, pyproject.toml, src-python/main.py
- https://github.com/refstudio/refstudio/issues/26
Adding ruff with its default settings as a pre-push hook for now. I imagine we'll want to tweak some settings later (like line length).
Once this is merged, devs will need to run:
```
$ poetry install
```
=> chore: add ruff for Python linting

CONTRIBUTING.md
* Related to https://github.com/refstudio/refstudio/issues/2
* Fixes https://github.com/refstudio/refstudio/issues/43
Adds the first version of CONTRIBUTING.md
=> chora: add contributing guidelines

package.json, scripts/remove_binary.sh
- #70 
Trying to rebuild the binary while some of these files are still around results in the new binary being created from older specs.
Running `yarn python` should take ~2 minutes to complete.
After running this script, there should be a single `main` file at `src-tauri/bin/python/main-aarch64-apple-darwin/` (the last directory name will be slightly different if you are not on a Mac).
=> bug: Update binary build script to first remove existing binary (#70)

scripts/reset_uploads.sh
Forgot to update `reset_uploads.sh` as part of #72 and #73
=> fix: prefix reset project storage directories with a dot

package.json, poetry.lock, pyproject.toml, python/sidecar/ingest.py, python/sidecar/shared.py, python/tests/test_ingest.py, python/tests/test_shared.py
=> fix: remove embedding creation from pdf ingestion

scripts/remove_binary.sh, scripts/reset_uploads.sh
Fixes #98 
- use `$HOME` instead of `~` in the path to get the valid path
- add `-f` to `rm "$PROJECT_DIR/uploads/"*.pdf` so that the script does not fail when the `uploads` directory is empty
=> fix: use home variable in script to reset uploads

src/atoms/referencesState.ts
Fixes #96 
Save references in local storage so that restarting/reloading the app does not reset the references list
=> feat: save references in local storage

src/TipTapEditor/TipTapEditor.css
Fixes #117 
Adds CSS rules to add bullet points/numbers for unordered and ordered list
=> fix: add back style rules for ordered and unordered lists

src/atoms/fileActions.ts, src/components/PanelSection.tsx, src/panels/ExplorerPanel.tsx
This PR closes issue #142 by adding a close all files action in the OPEN FILES panel.
=> feat: add button to close all files to Open Files panel

src/api/chat.test.ts, src/api/chat.ts, src/api/rewrite.ts, src/components/PrimarySideBar.test.tsx, src/components/TabPane.test.tsx, src/index.css, src/panels/AIPanel.tsx, src/panels/ai/ChatPanelSection.test.tsx, src/panels/ai/ChatPanelSection.tsx, src/panels/ai/SelectionPanelSection.tsx, tailwind.config.js, vite.config.ts
This PR closes #148 by adding a UI for chat interaction.
Note that currently the backend don't support threads and history (will be fixed by #144) so this PR adds that as a UI state in order to experiment the interaction pattern.
=> feat: add chat interaction UI

.github/workflows/on-push.yml
=> chore: Add coverage reporting for python sidecar

src/components/FileEntryTree.tsx, src/views/ReferenceView.tsx
Fixes #183 
This adds `useMemo` to memoize reference atom and prevent the infinite render loop
This also removes a duplicated key, that was triggering a warning message
=> fix: prevent infinite rerendering in reference view

src/atoms/core/paneGroup.ts, src/atoms/fileActions.test.ts, src/components/FileEntryTree.test.tsx, src/components/FileEntryTree.tsx, src/components/FileNode.tsx, src/components/FilesList.test.tsx, src/components/FilesList.tsx, src/components/PanelSection.tsx, src/panels/ExplorerPanel.tsx, src/panels/MainPanel.tsx
This improves the File Tree component:
- Hover and selected effects now take the whole width of pane
- Open files use a FilesList component instead of FileTree
- Directories are collapsible
Closes #195
=> feat: improve file tree

python/README.md, python/cli.schema.json, python/main.py, python/sidecar/cli.py, python/sidecar/ingest.py, python/sidecar/settings.py, python/sidecar/storage.py, python/sidecar/typing.py, python/tests/test_storage.py, src/api/types.ts
fixes #191 
___
```bash
$ poetry run python main.py delete --source_filenames grobid-fails.pdf "Machine Learning at Scale.pdf" | jq
{
"status": "ok",
"message": ""
}
$ poetry run python main.py delete --source_filenames file-does-not-exist.pdf | jq
{
"status": "error",
"message": "Unable to delete file-does-not-exist.pdf: not found in storage"
}
```
=> [Sidecar] Add ability to remove one or all references

src/atoms/core/paneGroup.ts, src/atoms/fileActions.test.ts
Fixes #205 
Removing the active file from a pane now updates the active file of the pane:
- makes the last file of the pane the new active file
- updates the field to `undefined` if there are no files left in the pane
=> fix: always keep a file as active file when possible

src-tauri/src/core/menu.rs, src/atoms/fileActions.ts, src/atoms/types/FileContent.ts, src/components/PanelSection.tsx, src/components/footer/Footer.tsx, src/components/footer/FooterItem.test.tsx, src/components/footer/FooterItem.tsx, src/events.ts, src/panels/MainPanel.tsx, src/panels/references/FilesDragDropZone.tsx, src/panels/references/ReferencesDropZone.test.tsx, src/panels/references/ReferencesFooterItems.test.tsx, src/panels/references/ReferencesFooterItems.tsx, src/panels/references/ReferencesList.tsx, src/panels/references/ReferencesPanel.test.tsx, src/panels/references/ReferencesPanel.tsx, src/panels/references/ResetReferencesInstructions.test.tsx, src/panels/references/ResetReferencesInstructions.tsx, src/panels/references/UploadTipInstructions.test.tsx, src/panels/references/UploadTipInstructions.tsx, src/settings/SettingsModalOpener.test.tsx, src/utils/test-utils.tsx, src/views/ReferencesTableView.test.tsx, src/views/ReferencesTableView.tsx
Adds table view of references. Check features implemented in #200.
Extra: Also adds the utility test method `mockListenEvent` to simplify tests of components that listen to events.
https://github.com/refstudio/refstudio/assets/174127/887abe32-546f-43af-9097-f6c30f116679
This closes https://github.com/refstudio/refstudio/issues/200
=> feat: "Table view" of many references in editor area

python/main.py, python/sidecar/ingest.py, python/sidecar/shared.py, python/tests/test_ingest.py, scripts/reset_uploads.sh
fixes #218 
Note that `IngestResponse` will still contain _all_ References, not just the newly uploaded Reference. Let me know if we want to change this.
______
```bash
$ ls -la $HOME"/Library/Application Support/com.tauri.dev/project-x/uploads"
total 5536
drwxr-xr-x  4 greg  staff      128 Jun 28 21:21 .
drwxr-xr-x  9 greg  staff      288 Jun 28 21:22 ..
-rw-r--r--@ 1 greg  staff   333450 Jun 28 15:24 Machine Learning at Scale.pdf
-rw-r--r--@ 1 greg  staff  2497316 Jun 28 15:36 grobid-fails.pdf
$ poetry run python main.py ingest --pdf_directory=$HOME"/Library/Application Support/com.tauri.dev/project-x/uploads"
2023-06-28 21:22:47,767 - sidecar.ingest - INFO - Grobid successfully parsed file: Machine Learning at Scale.pdf
2023-06-28 21:22:47,767 - sidecar.ingest - WARNING - Grobid failed …
```
=> feat: Update ingest so uploads are only processed once

src/features/textEditor/components/tipTapNodes/collapsibleBlock/helpers/unsetPartiallySelectedCollapsibleBlocks.test.ts, src/features/textEditor/components/tipTapNodes/collapsibleBlock/inputRuleHandlers/chevronHandler.test.ts, src/features/textEditor/components/tipTapNodes/collapsibleBlock/keyboardShortcutCommands/enter.test.ts, src/features/textEditor/components/tipTapNodes/collapsibleBlock/keyboardShortcutCommands/modEnter.test.ts, src/features/textEditor/components/tipTapNodes/collapsibleBlock/nodes/CollapsibleBlockNode.test.ts, src/features/textEditor/components/tipTapNodes/test-fixtures.ts
We had to skip a failing test in a previous PR (#215). Debugging the issue was difficult because the test was not using the util function `setUpEditorWithSelection`.
This PR adds the function to all the existing tests, to make the tests more legible
=> chore: use setUpEditorWithSelection in all tests

python/README.md, python/cli.schema.json, python/sidecar/ingest.py, python/sidecar/shared.py, python/sidecar/typing.py, python/tests/fixtures/data/references.json, python/tests/test_ingest.py, python/tests/test_shared.py, src/api/ingestion.test.ts, src/api/ingestion.ts, src/api/types.ts
fixes #190 
____
Discussed this with @cguedes and it makes more sense for us to consider the `source_filename` to be the true unique id of the Reference file, since that implicitly happens on the filesystem anyway.
=> Remove filename_md5 from backend

python/sidecar/ingest.py, python/tests/test_ingest.py
fixes #222 and related to #112 
________
In addition to fix the bug that resulted in citation keys for existing references being changed upon upload of new, conflicting key references, another change is that a citation key will _always_ begin in its "unappended" form (e.g. reda2023). This is required to maintain consistency in the event of a new upload that conflicts.
Example: Uploading two new references that would have a citation key of `reda2023`.
```
Prior to this PR - `reda2023a`, `reda2023b`
Upon merge - `reda2023`, `reda2023a`
```
=> fix: citation keys should not update on key collision with newly uploaded references

src/atoms/__tests__/fileEntryActions.test.ts, src/atoms/fileEntryActions.ts, src/io/filesystem.ts, src/wrappers/EventsListener.tsx, src/wrappers/__tests__/EventsListener.newFile.test.tsx
We are currently using absolute paths everywhere, but should not be aware of this absolute path.
This also leads to issues, like being forced to make functions async only to get the base directory, like the atom to create a new file.
This PR fixes the issue by only using relative path: `filesystem` functions strip out the base directory from returned path, and add it back when trying to read or write files
=> feat: use only relative paths in the app

src/application/App.tsx, src/components/PrimarySideBar.tsx, src/components/footer/Footer.tsx
This removes the top border of the footer and the bottom border of the collapsed AI panel
Before:
After:
=> fix: remove footer border

src/application/sidebar/ExplorerPanel.tsx, src/application/sidebar/FileExplorer.tsx, src/application/sidebar/__tests__/FileExplorer.test.tsx, src/atoms/editorActions.ts, src/atoms/fileEntryActions.ts, src/features/references/__tests__/test-fixtures.ts, src/features/references/sidebar/ReferencesPanel.tsx, src/io/filesystem.ts
Fixes #246 
This creates a new atom to open the PDF file corresponding to a reference. The atom checks that the reference exists and then call the `openFilePathAtom`, assuming that the PDF lives in the uploads directory
=> fix: open pdf from references with filename

src/features/references/editor/ReferencesTableView.tsx, src/features/references/editor/__tests__/ReferencesTableView.test.tsx
This PR adds two new buttons for each references row to open reference details and reference PDF
Related to https://github.com/refstudio/refstudio/issues/159 and https://github.com/refstudio/refstudio/issues/201
=> 159-add-missing-table-row-buttons

.husky/pre-push
This adds `yarn knip` to our pre-push hooks
I made `yarn knip` run before `yarn test` because it runs faster so the pre-push hooks will fail faster in case knip fails
Closes #258
=> chore: add knip to pre-push hooks

.husky/pre-push
Now we have added knip to `yarn check` (#268), the pre-push hooks run the script twice, as it runs `yarn check` then `yarn knip`
This simply removes `yarn knip` from the pre-push hooks
=> chore: remove duplicated knip check

python/sidecar/rewrite.py, python/sidecar/shared.py, python/tests/test_shared.py
fixes #294
We still won't be able to catch all edges with this function, but we will at least handle this case now.
=> fix: bug where full prompt is included in completion response

.env.example, poetry.lock, pyproject.toml, python/cli.schema.json, python/main.py, python/sidecar/chat.py, python/sidecar/rewrite.py, python/sidecar/typing.py, python/tests/conftest.py, python/tests/test_chat.py, python/tests/test_rewrite.py, scripts/reset_uploads.sh, src/api/__tests__/chat.test.ts, src/api/__tests__/rewrite.test.ts, src/api/__tests__/sidecar.test.ts, src/api/chat.ts, src/api/rewrite.ts, src/api/sidecar.ts, src/api/types.ts, src/features/ai/settings/OpenAiSettingsPane.tsx, src/features/ai/settings/__tests__/OpenAiSettingsPane.test.tsx, src/settings/__tests__/settings.test.ts, src/settings/panes/__tests__/DebugSettingsPane.test.tsx, src/settings/settingsManager.ts
@cguedes @sehyod I pushed this with `no-verify` since I figured we might have some discussion on the typing changes. Leaving as draft for now, but please feel free to add your feedback.
______
fixes #85 and allows errors to be return within the sidecar response types
For now, I'm passing through the exception in the `message`, but I figured this PR would lead to some follow-up discussion on what we'd want to see on errors.
_____
*Ok*
```
{
"status": "ok",
"message": "",
"choices": [
{
"index": 0,
"text": "ML engineering is an experimental and iterative discipline, unlike traditional software engineering. Despite the negative perception of many failed experiments and models not being deployed, it is acceptable for them to not reach production."
}
]
}
```
*Error*
```
{
"status": "error", …
```
=> feat: Handle errors, retries, and improve response types

src/api/completion.ts, src/application/components/MainPanel.tsx, src/features/references/components/ReferencesItemStatusLabel.tsx, src/features/textEditor/components/TipTapEditor.css, src/features/textEditor/components/tipTapEditorConfigs.ts, src/features/textEditor/components/tipTapNodes/plugins/__tests__/sentenceCompletion.test.tsx, src/features/textEditor/components/tipTapNodes/plugins/helpers/sentenceCompletionCommand.ts, src/features/textEditor/components/tipTapNodes/plugins/sentenceCompletion.ts, src/features/textEditor/components/tipTapNodes/types/SentenceCompletionMetadata.ts, src/features/textEditor/components/tipTapNodes/types/SentenceCompletionState.ts, src/index.css, src/lib/assertNever.ts, tailwind.config.js
This adds the shortcut cmd+J to run sentence completion in the editor.
The completion only runs if the selection is empty. The text sent as input for the LLM is the text between the beginning of the current block (current draggable block, current list item, etc.) and the position of the cursor.
=> Sentence completion in the editor

src-tauri/src/main.rs
Fixes #315 
**Problem**
Changing files while developing causes the app to reload. Sometimes, the app is being re-rendered, and tries to close the splashscreen. Since the splashscreen is not open, the app crashes.
**Solution**
Hide the splashscreen instead of closing it
=> fix: hide splashscreen instead of closing

python/README.md
Minor changes -
- Sidecar needs the openai env variables setup before someone can test the AI features using poetry
- minor formatting fixes: removed $ for easier copying of commands.
=> Tauri sidecar README fixes and added open ai env variables

python/README.md, python/cli.schema.json, python/sidecar/ingest.py, python/sidecar/typing.py, python/tests/test_ingest.py, src/api/types.ts
Adds `doi` field from grobid extraction to the `references.json`. For most papers this can be used to link to other databases mentioned in https://github.com/refstudio/refstudio/issues/140
=> doi extraction for linking to external databases

python/sidecar/shared.py
sometimes the backend is not able to chunk the full text from the pdfs because of file not found errors.
=> chore(backend): added logging to chunking

src/features/textEditor/components/tipTapNodes/notionBlock/NotionBlockNode.ts, src/features/textEditor/components/tipTapNodes/notionBlock/commands/indent.ts, src/features/textEditor/components/tipTapNodes/notionBlock/commands/unindent.ts
**Problem**
`indent` and `unindent` commands were returning `true` to block default behavior of `Tab` and `Shift-Tab` shortcuts. However this made the `Backspace` command believe that the content could be unindented, blocking the fallback behavior of the shortcut, which is merging the line with the previous one.
**Solution**
This changes the return result of `indent` and `unindent` commands back to the proper boolean indicating whether the command can run.
`Tab` and `Shift-Tab` shortcuts are now the one responsible for returning `true` to block the default behavior of these shortcuts.
Fixes #342
=> fix: make indent commands return proper command result

src/features/textEditor/components/tipTapNodes/notionBlock/NotionBlock.tsx, src/features/textEditor/components/tipTapNodes/notionBlock/inputRuleHandlers/createNotionBlockInputRule.ts
Turning a collapsible block into an ordered or unordered list item did not uncollapse the block first, making its content invisible and impossible to bring back
=> fix: uncollapse collapsible blocks when changing type

.vscode/settings.json, README.md, index.html, package.json, python/sidecar/http.py, src/api/sidecar.ts, src/atoms/projectState.ts, vite.config.ts
This PR fixes #380 that allows the web application to call the sidecar commands via HTTP interface.
Also adds utility startup scripts and updates README.md
=> feat: web call sidecar http

.husky/pre-push, package.json, python/sidecar/projects.py
@gjreda I've just noticed that the #389 is failing in the CI after merge agains main!
This PR adds an utility to run python tests from the project root using yarn `yarn python:tests` and updates the git push hook to also run python tests.
@gjreda please fix the error reported in #391 (I don't know how 😅).
_____
fixes #391
=> feat: Add python tests script and run python tests in pre-push

.vscode/settings.json
Forked off of #368. This hides these "inlay hints" (the text with the gray background) which makes it much easier to tell what's actually in your Rust code:
=> Disable inlay hints in Rust

src/application/sidebar/LeftSidePanelWrapper.tsx, src/application/sidebar/RightSidePanelWrapper.tsx, src/components/TabCloseButton.tsx, src/components/VerticalResizeHandle.tsx, src/components/icons.tsx, tailwind.config.js
This makes the resize handles for sidebars transparent (only visible when hovering them)
https://github.com/refstudio/refstudio/assets/58954208/41fcdfa6-ba52-4614-beee-fbd39e767d13
This also replaces the icons for close button and unsaved changes circle to use custom icons created by the design team
Fixes #409
=> fix: address comments from design

python/generate_schema.py, python/sidecar/http.py, python/web.py
=> Add api for search

splashscreen.html
This adds the Roboto font import statement to the splashscreen file
Fixes #436
=> fix: use roboto font in splashscreen

package.json, python/api.schema.json, python/openapi.json, python/sidecar/chat.py, python/sidecar/http.py, python/sidecar/pydantic_utils.py, python/sidecar/rewrite.py, python/sidecar/settings.py, python/sidecar/typing.py, python/tests/test_http.py, python/tests/test_settings.py, src/AppStartup.tsx, src/api/__tests__/sidecar.test.ts, src/api/api-paths.ts, src/api/api-types.ts, src/api/sidecar.ts, src/api/typed-api.ts, src/application/listeners/projectEventListeners.ts, src/features/ai/settings/OpenAiSettingsPane.tsx, src/features/ai/settings/__tests__/OpenAiSettingsPane.test.tsx, src/features/components/RewriteWidget.tsx, src/features/components/__tests__/RewriteWidget.test.tsx, src/settings/panes/GeneralSettingsPane.tsx, src/settings/panes/__tests__/DebugSettingsPane.test.tsx, src/settings/panes/__tests__/GeneralSettingsPane.test.tsx, src/settings/settingsManager.ts, yarn.lock
This solves the problem with optional fields in `SettingsSchema` in TypeScript.
In general I think we should avoid specifying default values in Pydantic models that are part of the HTTP API because the semantics are unclear. If you have something like:
```py
class Settings(RefStudioModel):
a: str = 'alice'
b: str = 'bob'
@settings_api.put("/")
async def update_settings(req: SettingsSchema) -> SettingsSchema:
...
```
Then if the users hits the PUT endpoint with `{"a": "archer"}`, presumably their intention is to just set "a" to "archer" and not also set "b" to "bob".
Highlights:
- I "flattened" the settings schema like we talked about last week. The new model is `FlatSettingsSchema` and it has no `Optional` fields or fields with default values.
- I found [this decorator][1] to be the best …
=> Create distinct types for Settings / SettingsPatch

src/application/components/SideBar.css, src/application/sidebar/FileExplorer.tsx, src/application/sidebar/LeftSidePanelWrapper.tsx, src/application/sidebar/RightSidePanelWrapper.tsx, src/application/sidebar/icons.tsx, tailwind.config.js
This adds the shadow box for sidebars and adds a transition animation on the arrow when collapsing/uncollapsing a folder in the explorer
Closes #467
=> fix: sidebar shadow and folder collapsing animation

knip.ts
=> chore: ignore openapi-tyepscript in knip config

python/api.schema.json, python/openapi.json, python/sidecar/http.py, python/sidecar/search.py, python/sidecar/typing.py, python/tests/test_http.py, python/tests/test_search.py, src/api/__tests__/ingestion.ingest.test.ts, src/api/__tests__/typed-api.test.ts, src/api/api-paths.ts, src/api/api-types.ts, src/api/ingestion.ts, src/api/projectsAPI.ts, src/api/typed-api.ts
I filled in the FastAPI / Pydantic schemas in a few places. Note that POST requests need a JSON payload with this system. If we want to support empty payloads, we'll need to add some more logic in `typed-api.ts`.
=> Port a few more endpoints to the typed API

python/api.schema.json, python/openapi.json, python/sidecar/settings.py, python/sidecar/typing.py, src/api/__tests__/sidecar.test.ts, src/api/api-paths.ts, src/api/api-types.ts, src/settings/panes/__tests__/DebugSettingsPane.test.tsx
=> feat: Add active project id to settings

src/application/views/WelcomeView.tsx, src/components/Button.tsx, src/features/components/RewriteOptionsView.tsx, src/features/references/components/icons.tsx, src/features/references/sidebar/ReferencesList.tsx, src/features/references/sidebar/ReferencesPanel.tsx, src/features/references/sidebar/__tests__/ReferencesPanel.test.tsx, tailwind.config.js
This implements the design for the references panel when no reference has been ingested
Closes #474
=> feat: implement design for empty references panel

src/features/textEditor/components/tipTapNodes/notionBlock/NotionBlock.css, src/features/textEditor/components/tipTapNodes/notionBlock/NotionBlock.tsx
There were 2 issues:
- The spacing between list items was 0 instead of being the same as the spacing between a parent node and its child, resulting in a weird shifting behaviour when indenting/un-indenting an item in a list
- The spacing between list items was different from the spacing between collapsible nodes.
The first issue was a bug and has been fixed. The second one was more or less intended: the design specifies that there should be 24px between each node:
I have changed that to make collapsible nodes considered as list items (which makes sense because that is how we export them in markdown). However, the default spacing remains 24px, which means that turning a regular node into a collapsible node still results in things moving up and down: …
=> fix: margin between sibling list items

src/AppStartup.tsx, src/__tests__/AppStartup.test.tsx, src/application/components/ProjectsList.tsx, src/application/components/__tests__/ProjectsList.test.tsx, src/application/components/__tests__/test-fixtures.ts, src/application/components/icons.tsx, src/application/listeners/projectEventListeners.ts, src/application/views/WelcomeView.tsx, src/atoms/projectState.ts, tailwind.config.js
This implements the empty view for the welcome screen (when the user has no project)
This loads the list of projects in an atom during app startup, so that the list is already available when displaying the welcome view
Closes #499
=> feat: add empty welcome view

src/api/api.ts, src/io/filesystem.ts, src/wrappers/EventsListener.tsx, src/wrappers/tauri-api-stubs/path.ts, src/wrappers/tauri-wrapper.ts
This closes #456 by exporting the references (.bib) to the exports folder inside the project. It will also close and open the exported file to provide user feedback.
Note: We need to close and open the file because otherwise the editor content won't update.
=> feat: export references behaviour for web (and desktop)

src/application/sidebar/LeftSidePanelWrapper.tsx, src/application/sidebar/RightSidePanelWrapper.tsx
**Problem**
Resizable panels' layout is stored in local storage. When starting the app with sidebars uncollapsed, the library will force them to be uncollapsed, even if the sidebar should be disabled.
**Solution**
Prevent the automatic uncollapse action performed by the library when the sidebar is disabled.
Fixes #486
=> fix: prevent panel from uncollapsing when sidebar is disabled

src/application/components/OpenEditorsTabPane.tsx, src/application/components/icons.tsx, src/application/listeners/projectEventListeners.ts, src/application/views/WelcomeView.tsx, src/components/TabPane.tsx
This removes the left buttons in the empty welcome screen:
This also removes the Tips&Tricks collapsible in the default view:
Finally, this refreshes the `allProjectsAtom` after creating a Sampl project (this had been forgotten when implementing #500)
Closes #475
=> feat: update welcome screen

src/api/projectsAPI.ts, src/io/__tests__/filesystem.test.ts, src/io/filesystem.ts
=> Remove the dependency on @tauri-apps/api/fs

src/features/textEditor/components/tipTapNodes/notionBlock/NotionBlockNode.ts
=> feat: add star shortcut to create unordered lists

.github/actions/setup-node/action.yml, .github/actions/setup-python/action.yml, .github/workflows/on-push.yml
I think we had some issues with our cache and removing it fixed the failing CI.
This PR is removing the unnecessary installation of pytest via pip (pytest is installed via poetry in setup-python)
This is also improving our CI by caching poetry so that python jobs now take half of the time they use to take:
Before the PR:
After the PR:
=> fix: activate venv instead of using poetry run

.vscode/launch.json, python/sidecar/config.py
This PR fixes #523 and also fixes the VSCode launch.json configuration for "Python: FastAPI"
=> chore: sidecar enable logging flag is inverted

python/api.schema.json, python/openapi.json, python/sidecar/filesystem/router.py, python/sidecar/filesystem/schemas.py, python/sidecar/filesystem/service.py, python/sidecar/meta/router.py, python/sidecar/projects/router.py, python/sidecar/projects/schemas.py, python/sidecar/projects/service.py, python/sidecar/typing.py, python/tests/ai/test_router.py, python/tests/conftest.py, python/tests/filesystem/test_router.py, python/tests/projects/test_router.py, python/tests/projects/test_service.py, python/tests/references/test_router.py, scripts/reset_refstudio.sh, src/api/api-paths.ts, src/api/api-types.ts, src/api/projectsAPI.ts
fixes #510 
@cguedes the following endpoints are still showing up as `unknown`:
- `read_file_api_fs__project_id___filepath__get` -- I suspect this has something to do with this endpoint returning fastapi's `FileResponse` rather than our own definition. I tried wrapping `FileResponse`, but no luck.
- `head_file_api_fs__project_id___filepath__head` -- doesn't return anything
- `shutdown_api_meta_shutdown_post` -- doesn't return anything
=> feat: Add missing api response types

src/application/components/MainPanel.tsx, src/features/textEditor/components/TipTapEditor.css
This applies the max-width to the text editor, and not the content only, to make the left indent fixed
Closes #528 and #482
=> feat: apply max width to editor instead of content only

src/atoms/__tests__/editorActions.test.ts, src/atoms/__tests__/notificationsState.test.ts, src/atoms/__tests__/paneActions.test.ts, src/atoms/__tests__/selectionState.test.ts, src/atoms/core/createEditorContentAtoms.ts, src/atoms/hooks/__tests__/useAnyEditorDataIsDirty.test.ts, src/atoms/hooks/useAnyEditorDataIsDirty.ts, src/components/TabPane.tsx, src/components/footer/Footer.tsx, src/features/ai/sidebar/__tests__/ChatPanel.test.tsx, src/features/ai/sidebar/__tests__/RewriterPanel.test.tsx, src/features/textEditor/footer/FooterSavingFilesItem.tsx, src/features/textEditor/footer/__tests__/FooterSavingFilesItem.test.tsx, src/settings/__tests__/SettingsModalOpener.test.tsx, src/test/test-utils.tsx
Auto-save documents
https://github.com/refstudio/refstudio/assets/174127/15a97306-8e48-4156-a490-ec2cd950c666
This is related to #484
=> feat: consider auto save for documents

src/atoms/core/createEditorContentAtoms.ts, src/atoms/core/editorData.ts, src/atoms/hooks/__tests__/useAnyEditorDataIsDirty.test.ts, src/atoms/hooks/useSomeEditorIsBeingSaved.ts, src/atoms/types/EditorData.ts, src/features/textEditor/footer/FooterSavingFilesItem.tsx, src/features/textEditor/footer/__tests__/FooterSavingFilesItem.test.tsx
**Problems**
- We were using `isDirty` flag to determine whether some files were being saved. However a new file is dirty but is not being saved.
- The debounced saving function was using the `editorId` instead of the atom. So after renaming a file, the id that was used was outdated.
**Solutions**
- Create a `isContentBeingSaved` flag in EditorData. The flag is set to `true` when updating the buffer and set to `false` after saving (even if the save operation failed)
- Use the `EditorIdAtom` in the debounced save function
Fixes #564
=> fix: prevent the saving spinner from showing up when it should not

src/application/sidebar/LeftSidePanelWrapper.tsx, src/application/sidebar/RightSidePanelWrapper.tsx
This computes the percentage corresponding to 256px to give a min width to sidebar panels
In a next release `react-resizable-panels` should add support for using pixels unit directly (cf. https://github.com/bvaughn/react-resizable-panels/pull/176). This PR is a temporary solution.
=> feat: add min width to sidebars

src/features/textEditor/components/tipTapNodes/notionBlock/NotionBlockNode.ts, src/features/textEditor/components/tipTapNodes/notionBlock/plugins/blockBrowsingPlugin.ts
Fixes #586
This changes the logic when moving a block up/down.
Now the block is indented only when its sibling is a list item, an uncollapsed collapsible block or a regular block with children. Otherwise, the block moves before/after its sibling.
https://github.com/refstudio/refstudio/assets/58954208/976144bf-0363-48dc-8292-ad7144360115
=> fix: do not indent blocks when moving them

src/features/textEditor/components/tipTapNodes/notionBlock/plugins/blockBrowsingPlugin.ts
This prevents the events from bubbling and default behaviour inside block navigation.
Related to #584
=> fix: Prevent events from bubbling inside block navigation

package.json
Configure a new release cycle for `23.3.0-next` so that we can test builds in the GH actions.
=> chore: Bump version to 23.3.0-next
