python/sidecar/ingest.py, python/tests/test_ingest.py
=> Prefix project storage directories with a dot (#72)

scripts/remove_binary.sh
Also don't remove all *.spec files bc we might be removing files we don't want
=> Ensure main.spec exists before removing

.vscode/settings.json, src/TipTapEditor/TipTapEditor.css
This PR improves #117 and adds auto format for CSS and PostCSS files.
=> fix-improve-css-for-html-lists

python/tests/test_shared.py
=> Fix tests from PR #235

python/sidecar/ingest.py, python/sidecar/settings.py, python/sidecar/storage.py
=> Make sidecar logging centralized

README.md
Improve README.md with instructions on how to reset.
=> Add reset instructions

README.md
per discussion on Slack: https://ref-studio.slack.com/archives/C05525DV9HN/p1688073731928759
=> Add data reset to instructions

python/main.py
fix import issue introduced by #260
=> Fix import issue

src/features/references/editor/ReferencesTableView.tsx
- shalow clone rowData for the AgGridReact
- select the correct date editor
=> fix: edit operation for references

python/README.md, python/cli.schema.json, python/main.py, python/sidecar/prompts.py, python/sidecar/rewrite.py, python/sidecar/shared.py, python/sidecar/typing.py, python/tests/test_prompts.py, python/tests/test_rewrite.py, python/tests/test_shared.py, src/api/types.ts
fixes #284 
Some notes:
- The front-end can optionally pass in additional context of `title` and `abstract` to further steer the model.
- The response should always begin with the last portion of the input text.
- ~I'm reusing `RewriteChoice` as a return type since this is more or less very similar functionality to what we're doing with text rewrites.~
- I made `n_choices`, `max_tokens`, `temperature` adjustable.
- OpenAI advises keeping `max_tokens` > 256 ([here](https://platform.openai.com/docs/guides/gpt/inserting-text)). I find this can lead to some pretty long outputs, but maybe that's ok. If we want to shorten the output, I think it's better to have a longer response from the LLM and allow the front-end to trim it as we see fit.
________
```bash
$ poetry run python main.py …
```
=> feat: Add text completion endpoint to sidecar

src-tauri/src/main.rs, src-tauri/tauri.conf.json, src/settings/SettingsModal.tsx
This will close https://github.com/refstudio/refstudio/issues/261
=> feat: update tauri bundle identifier

python/sidecar/chat.py, python/sidecar/rewrite.py, python/sidecar/typing.py
fixes #299 
Including the full text responses from the API might be overkill, but I figured better to err on the side of too much info for now and then we can pare it back.
_________
<details>
```
2023-07-13 13:41:50,414 - root - INFO - Calling rewrite with the following parameters: {'text': 'ML engineering, as a discipline, is highly experimental and itera- tive in nature, especially compared to typical software engineering. Contrary to popular negative sentiment around the large numbers of experiments and models that don’t make it to production, we found that it’s actually okay for experiments and models not to make it to production.', 'n_choices': 3, 'temperature': 0.7}
2023-07-13 13:41:50,414 - root - INFO - Calling OpenAI chat API with the following input message(s): [{'role': …
```
=> chore: Add info logging to sidecar for ai interactions

src/application/App.tsx
This PR improves the sidebar panel width behaviour and closes #320.
https://github.com/refstudio/refstudio/assets/174127/f318a4ca-5f38-4379-9ba1-2287a319ee43
=> feat: Make refstudio side panels to keep their width on resize

python/sidecar/ingest.py
=> Update ingest to only use grobid for header parsing

python/main.py, python/sidecar/chat.py, python/sidecar/ingest.py, python/sidecar/rewrite.py, python/sidecar/search.py, python/sidecar/storage.py, python/tests/test_chat.py, python/tests/test_ingest.py, python/tests/test_rewrite.py, python/tests/test_search.py, python/tests/test_storage.py
=> Separate cli interprocess comms from functionality

python/generate_schema.py, python/sidecar/chat.py, python/sidecar/http.py, python/sidecar/rewrite.py
=> feat: Add dependency on settings for AI endpoints

python/api.schema.json, python/main.py, python/sidecar/http.py, python/tests/test_http.py, python/web.py, src/api/api-types.ts
=> Remove legacy sidecar CLI and HTTP methods

python/sidecar/http.py, python/sidecar/storage.py, python/tests/test_http.py
=> bug: Handle exception if a user tries to view references before any have been ingested

README.md, package.json, scripts/reset_refstudio.sh, scripts/reset_uploads.sh
This closes #449 by adding a new script to reset refstudio
=> chore: Add a reset_refstudio.sh script and update README.md

.github/actions/setup-python/action.yml
=> fix: remove poetry cache

src/atoms/__tests__/fileExplorerActions.test.ts, src/atoms/core/fileExplorerEntry.ts
This changes the order in the file explorer to make files appear first
Close #536
=> feat: make files appear before folders

python/sidecar/config.py
=> chore: Log to console and file

python/sidecar/ai/chat.py, python/tests/ai/test_chat.py, python/tests/conftest.py
=> fix: Display helpful message when chat happens without references

src/features/textEditor/components/tipTapNodes/notionBlock/NotionBlock.css, src/features/textEditor/components/tipTapNodes/notionBlock/plugins/collapsibleArrowPlugin.ts
This fixes #585 and fixes #588
=> fix: list text should indent when wrapped

src/features/components/icons.tsx
=> fix: disabled click to pause lottie animation
